name: Z-FFA
main: xyz.zcraft.studios.zffa.ZFfaPlugin
version: 1.3.0
api-version: '1.21'
author: ZCraft Studios
website: https://studio.z-craft.xyz
softdepend:
  - PlaceholderAPI
  - Multiverse-Core
  - Vault
  - LuckPerms
  - Essentials
  - PluginMetrics
commands:
  zffa:
    description: Z-FFA admin command.
    usage: /zffa
  ffa:
    description: Player FFA command.
    usage: /ffa
  duel:
    description: Player duel command.
    usage: /duel
  party:
    description: Party command.
    usage: /party
permissions:
  zf.admin:
    description: Access to Z-FFA admin commands.
    default: op
  zf.player:
    description: Access to Z-FFA player commands.
    default: true
  zf.kit.*:
    description: Access to every Z-FFA kit.
    default: op
  zf.viparena:
    description: Access to VIP FFA arenas.
    default: op
